server:
  port: 8090

spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/project?serverTimezone=UTC
    url: jdbc:mysql://localhost:3306/project?allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: kaimen
